name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
        cache: "pip"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Tests (Pytest)
      env:
        OPENAI_API_KEY: "sk-fake-key-para-las-github-actions"
      run: |
        pytest

  build-docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Construir imagen de Docker
      run: docker build -t azure-rag-api:latest .